# Generated by Django 5.1.7 on 2025-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='values',
            field=models.CharField(max_length=100),
        ),
    ]
